# Your name and what you do
name: Tom Finkelson
bio: Software Developer

description: Tom Finkelson's Personal Website

# Profile picture
#picture:

# your url: http://USERNAME.github.io
url: https://TFink7.github.io

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
#twitter: mytwitter
linkedin: https://www.linkedin.com/in/tomfinkelson/
github: https://github.com/TFink7
email: tom.finkelson@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: true

# add your skills here
skills-list:
    - C#, Python
    - SQL
    - Linux
    - Git
    - Docker
    - MySQL/SQLite/EF Core/SQLAlchemy
    - Agile

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    WallpaperGenerator:
        name: Wallpaper Generator
        description: AI powered windows application that generates daily wallpapers based on a users location and current weather conditions.
        url: https://github.com/TFink7/WallPaperGenerator
    RobotShooter:
        name: Robot Shooter 
        description: OpenGL based turret defense game with custom shaders. 
        url: https://github.com/TFink7/RobotShooter


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true

gems:
    - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
